#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13
TOTAL_MINUTES=85

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd "$SCRIPT_DIR/../.." && pwd)
ENV_FILE="$ROOT_DIR/.env.scaleway"
INFRA_DIR="$ROOT_DIR/infra/scaleway"
REPOSITORY="henrikgrubbe/memes"
umask 077

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    warn "$1 is required before this wizard can continue."
    exit 1
  fi
}

select_container_cli() {
  if command -v docker >/dev/null 2>&1; then
    CONTAINER_CLI=docker
  elif command -v podman >/dev/null 2>&1; then
    CONTAINER_CLI=podman
  else
    warn "Docker or Podman is required before this wizard can continue."
    exit 1
  fi

  if ! "$CONTAINER_CLI" info >/dev/null 2>&1; then
    warn "$CONTAINER_CLI is installed but its container runtime is not running."
    exit 1
  fi
}

export_tofu_env() {
  export SCW_ACCESS_KEY SCW_SECRET_KEY SCW_DEFAULT_PROJECT_ID
  export TF_VAR_project_id="$SCW_DEFAULT_PROJECT_ID"
  export TF_VAR_github_webhook_secret
  export TF_VAR_github_fine_grained_pat
  export TF_VAR_slack_webhook_url
  export TF_VAR_openai_api_key
  export TF_VAR_xai_api_key
  export TF_VAR_image_tag
}

get_processing_backend() {
  gh variable list --repo "$REPOSITORY" --json name,value \
    --jq '.[] | select(.name == "MEME_PROCESSING_BACKEND") | .value'
}

set_processing_backend() {
  local expected="$1" actual
  if ! gh variable set MEME_PROCESSING_BACKEND \
    --repo "$REPOSITORY" --body "$expected"; then
    warn "Could not transfer processing authority to $expected."
    exit 1
  fi
  if ! actual=$(get_processing_backend) || [[ "$actual" != "$expected" ]]; then
    warn "Authority verification failed: expected $expected, observed ${actual:-unset}."
    exit 1
  fi
  printf '  %s✓ set%s GitHub variable MEME_PROCESSING_BACKEND=%s\n' \
    "$GREEN" "$RESET" "$expected"
}

apply_stage() {
  local plan_file
  plan_file=$(mktemp)
  CURRENT_PLAN_FILE="$plan_file"
  if ! tofu -chdir="$INFRA_DIR" plan -out="$plan_file"; then
    rm -f "$plan_file"
    CURRENT_PLAN_FILE=""
    return 1
  fi
  if ! confirm "$1"; then
    rm -f "$plan_file"
    CURRENT_PLAN_FILE=""
    warn "Apply cancelled. This plan made no infrastructure changes."
    return 1
  fi
  if ! tofu -chdir="$INFRA_DIR" apply "$plan_file"; then
    rm -f "$plan_file"
    CURRENT_PLAN_FILE=""
    return 1
  fi
  rm -f "$plan_file"
  CURRENT_PLAN_FILE=""
}

restore_actions_after_failed_cutover() {
  [[ "${CUTOVER_AUTHORITY_MOVED:-false}" == "true" ]] || return 0
  CUTOVER_AUTHORITY_MOVED=false
  warn "Cutover stopped before live ingress was confirmed. Restoring Actions authority."
  if ! gh variable set MEME_PROCESSING_BACKEND \
    --repo "$REPOSITORY" --body actions; then
    warn "Automatic recovery failed. Keep intake paused and run:"
    warn "gh variable set MEME_PROCESSING_BACKEND --repo $REPOSITORY --body actions"
  fi
}

CUTOVER_AUTHORITY_MOVED=false
CURRENT_PLAN_FILE=""
cleanup_wizard() {
  if [[ -n "$CURRENT_PLAN_FILE" ]]; then
    rm -f "$CURRENT_PLAN_FILE"
    CURRENT_PLAN_FILE=""
  fi
  restore_actions_after_failed_cutover
}
trap cleanup_wizard EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

banner "Scaleway hosted meme processing"

stage "Prerequisites and account safety" 8
say "You need a Scaleway account with MFA and billing enabled, plus Docker or Podman, OpenTofu, and GitHub CLI."
open_url "https://console.scaleway.com/"
step "Create or select the project, enable billing, and enable MFA for your user."
step "Use Scaleway's project settings page to copy the Project ID; UI labels may change."
open_url "https://www.scaleway.com/en/docs/identity-and-access-management/iam/how-to/enable-mfa/"
ask SCW_DEFAULT_PROJECT_ID "Paste the Scaleway Project ID:"
write_env SCW_DEFAULT_PROJECT_ID "$SCW_DEFAULT_PROJECT_ID"
write_env TF_VAR_project_id "$SCW_DEFAULT_PROJECT_ID"
select_container_cli
require_command gh
require_command tofu
if ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI must be authenticated before setup."
  exit 1
fi
note "The wizard leaves GitHub Actions authoritative until the final cutover stage."

stage "Scaleway deployment credentials" 6
say "Create a dedicated API key for deployment. It creates IAM, Queues, Registry, and Containers resources."
open_url "https://console.scaleway.com/iam/api-keys"
step "Follow the official API-key flow. Save the secret now; Scaleway reveals it only once."
ask SCW_ACCESS_KEY "Paste the access key:"
ask_secret SCW_SECRET_KEY "Paste the secret key:"
write_env SCW_ACCESS_KEY "$SCW_ACCESS_KEY"
write_env SCW_SECRET_KEY "$SCW_SECRET_KEY"

stage "Fine-grained GitHub token" 8
say "Create a short-lived fine-grained PAT restricted to henrikgrubbe/memes."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Select only the memes repository."
step "Grant Contents read/write and Issues read/write. Choose a short expiration and record a rotation reminder."
ask_secret TF_VAR_github_fine_grained_pat "Paste the fine-grained PAT:"
write_env TF_VAR_github_fine_grained_pat "$TF_VAR_github_fine_grained_pat"

stage "Runtime provider secrets" 7
say "Capture existing Slack/OpenAI credentials without writing them to tracked files."
open_url "https://platform.openai.com/api-keys"
ask_secret TF_VAR_openai_api_key "Paste the OpenAI API key:"
ask_secret TF_VAR_slack_webhook_url "Paste the Slack incoming webhook URL:"
ask_secret TF_VAR_xai_api_key "Paste the optional xAI fallback key, or leave empty:"
write_env TF_VAR_openai_api_key "$TF_VAR_openai_api_key"
write_env TF_VAR_slack_webhook_url "$TF_VAR_slack_webhook_url"
write_env TF_VAR_xai_api_key "$TF_VAR_xai_api_key"

stage "Webhook signing secret" 3
say "The same random value must be stored in Scaleway and supplied when the GitHub webhook is created."
if command -v openssl >/dev/null 2>&1; then
  TF_VAR_github_webhook_secret=$(_existing TF_VAR_github_webhook_secret || openssl rand -hex 32)
else
  ask_secret TF_VAR_github_webhook_secret "Paste a new high-entropy webhook secret:"
fi
write_env TF_VAR_github_webhook_secret "$TF_VAR_github_webhook_secret"
ask TF_VAR_image_tag "Immutable image tag [recommended: current commit SHA]:"
if [[ -z "$TF_VAR_image_tag" ]]; then
  TF_VAR_image_tag=$(git -C "$ROOT_DIR" rev-parse --short=12 HEAD)
fi
write_env TF_VAR_image_tag "$TF_VAR_image_tag"
export_tofu_env

stage "Phase one: registry and queues" 8
say "This phase creates the public registry, FIFO request queue, FIFO DLQ, and scoped SQS credentials."
say "It does not create containers, a queue trigger, a GitHub webhook, or change GitHub Actions."
export TF_VAR_deploy_containers=false
export TF_VAR_worker_trigger_enabled=false
tofu -chdir="$INFRA_DIR" init
if ! CURRENT_BACKEND=$(get_processing_backend); then
  warn "Could not read GitHub processing authority."
  exit 1
fi
if [[ "$CURRENT_BACKEND" == "hosted" ]]; then
  warn "Hosted processing is already authoritative. Full setup reruns are blocked to avoid an outage."
  say "Use the rotation and rollback procedures in docs/hosting-webhook.md instead."
  exit 1
fi
if tofu -chdir="$INFRA_DIR" state list 2>/dev/null | grep -q '^scaleway_container\.'; then
  note "Existing containers detected; preserving them and skipping the phase-one apply."
else
  apply_stage "Apply phase one to the selected Scaleway project?"
fi

stage "Build and push immutable images" 8
REGISTRY_ENDPOINT=$(tofu -chdir="$INFRA_DIR" output -raw registry_endpoint)
REGISTRY_HOST=${REGISTRY_ENDPOINT%%/*}
INGRESS_IMAGE="${REGISTRY_ENDPOINT}/webhook:${TF_VAR_image_tag}"
WORKER_IMAGE="${REGISTRY_ENDPOINT}/worker:${TF_VAR_image_tag}"
say "$CONTAINER_CLI will build both runtime images for linux/amd64 and push tag $TF_VAR_image_tag."
if ! confirm "Authenticate $CONTAINER_CLI and push both images to $REGISTRY_ENDPOINT?"; then
  warn "Image push cancelled."
  exit 1
fi
printf '%s' "$SCW_SECRET_KEY" | "$CONTAINER_CLI" login "$REGISTRY_HOST" --username nologin --password-stdin
"$CONTAINER_CLI" build --platform linux/amd64 --file "$INFRA_DIR/images/ingress.Dockerfile" --tag "$INGRESS_IMAGE" "$ROOT_DIR"
"$CONTAINER_CLI" build --platform linux/amd64 --file "$INFRA_DIR/images/worker.Dockerfile" --tag "$WORKER_IMAGE" "$ROOT_DIR"
"$CONTAINER_CLI" push "$INGRESS_IMAGE"
"$CONTAINER_CLI" push "$WORKER_IMAGE"

stage "Phase two: inert containers" 7
say "Create public ingress in off mode and a private worker in diagnostic mode."
say "The queue trigger remains absent, so deployment alone cannot consume or duplicate work."
export TF_VAR_deploy_containers=true
export TF_VAR_worker_trigger_enabled=false
export TF_VAR_hosted_ingress_mode=off
export TF_VAR_worker_mode=diagnostic
export TF_VAR_worker_diagnostic_response=success
apply_stage "Create the inert Serverless Containers?"

stage "Create the GitHub webhook" 5
INGRESS_ENDPOINT=$(tofu -chdir="$INFRA_DIR" output -raw ingress_endpoint)
say "GitHub must send issue events to ${INGRESS_ENDPOINT}/webhooks/github."
open_url "https://docs.github.com/en/webhooks/using-webhooks/creating-webhooks"
open_url "https://github.com/${REPOSITORY}/settings/hooks/new"
step "Use payload URL ${INGRESS_ENDPOINT}/webhooks/github and JSON content type."
step "Paste the signing secret saved as TF_VAR_github_webhook_secret in $ENV_FILE."
step "Select only Issues events and leave the webhook active."
pause "Press Enter only after GitHub reports a successful ping."

stage "No-side-effect trigger canary" 6
say "The hosted-canary label is excluded from Actions. Diagnostic worker mode never calls GitHub, Slack, or image providers."
if ! gh label create hosted-canary --repo "$REPOSITORY" \
  --description "Exclusive hosted-processing canary" --color BFD4F2 --force; then
  warn "Could not create or verify the reserved hosted-canary label."
  exit 1
fi
export TF_VAR_hosted_ingress_mode=canary
export TF_VAR_worker_mode=diagnostic
export TF_VAR_worker_diagnostic_response=success
export TF_VAR_worker_trigger_enabled=true
apply_stage "Enable the private diagnostic trigger and canary-only ingress?"
step "Create a NEW issue with the hosted-canary label already attached and a non-empty body."
step "Inspect worker logs: record method, path, content type, envelope shape, and one 200 delivery. Confirm the body is omitted from logs."
warn "If no request reaches the private worker, stop. Private-container trigger compatibility is not documented."
pause "Press Enter after recording the observed envelope and acknowledgement behavior."

stage "Retry and acknowledgement proof" 5
say "Use a fresh canary issue for each diagnostic. Never reuse a delivery that Actions processed."
export TF_VAR_worker_diagnostic_response=retry
apply_stage "Temporarily make diagnostics return HTTP 503?"
step "Create a NEW hosted-canary issue and record retry timing/count and final queue or DLQ state."
pause "Press Enter after the retry observation is complete."
export TF_VAR_worker_diagnostic_response=success
apply_stage "Restore successful diagnostic acknowledgement?"
step "Create one final NEW canary and verify it is not delivered again after 200."
pause "Press Enter after acknowledgement behavior is observed."

stage "Exclusive live canary" 10
say "This canary remains exclusive: the hosted-canary label makes Actions skip it while canary ingress admits it."
warn "Live mode calls an image provider, writes to GitHub, closes the issue, and posts to Slack."
step "Confirm the request queue has zero visible and zero in-flight messages; a prior 503 diagnostic can remain hidden for 240 seconds."
if ! confirm "Is the request queue fully drained, including in-flight messages?"; then
  warn "Live canary cancelled until the diagnostic queue is drained."
  exit 1
fi
export TF_VAR_worker_mode=live
if ! confirm "Enable live processing only for new hosted-canary issues?"; then
  warn "Live canary cancelled."
  exit 1
fi
apply_stage "Apply live worker mode while ingress remains canary-only?"
step "Create a NEW issue with hosted-canary attached before submission."
step "Use a valid body with Sender, Channel, Message, and Link fields. Do not reuse a diagnostic issue."
step "Verify exactly one provider call, output commit, issue completion, and Slack completion."
pause "Press Enter only after the exclusive live canary succeeds end to end."

stage "Reversible live cutover" 4
warn "This step changes the authoritative backend. Pause the Slack workflow or other issue intake first."
step "Confirm Actions has no running request and the request queue contains no pre-cutover canary."
if ! confirm "Is intake paused and are Actions and the queue drained?"; then
  warn "Cutover cancelled."
  exit 1
fi
export TF_VAR_worker_trigger_enabled=false
export TF_VAR_hosted_ingress_mode=canary
export TF_VAR_worker_mode=diagnostic
apply_stage "Detach the trigger before changing authority?"
CUTOVER_AUTHORITY_MOVED=true
set_processing_backend hosted
export TF_VAR_hosted_ingress_mode=live
if ! apply_stage "Open live ingress while the trigger is detached so new requests buffer?"; then
  exit 1
fi
CUTOVER_AUTHORITY_MOVED=false
warn "From this point, queued requests are awaiting hosted processing."
export TF_VAR_worker_mode=live
export TF_VAR_worker_trigger_enabled=true
apply_stage "Activate the live worker at maximum scale one?"
step "Resume intake and watch the first live request through queue, worker, GitHub commit, issue closure, and Slack notification."

finish
